name: maveninstall
on: pull_request

jobs:
  installmaven:
    runs-on: ubuntu
    steps:
      - name: install java
        run: sudo yum update -y && sudo yum install java -y
      - name: install maven
        run: sudo yum install maven -y
     




