name: mymavenbuild 
on: push
jobs:
  installmaven:
    runs-on: self-hosted
    steps:
      - name: installjava
        run: sudo yum update -y && sudo yum install java -y
      - name: install maven 
        run: sudo yum install maven -y  